name: BUILD
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
#    - name: Cache
#      uses: actions/cache@v3
#      with:
#        key: potatoes
#        path: .cache/
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Download arm gcc toolchain
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc-arm-none-eabi
        version: 1.0
        execute_install_scripts: true
#    - name: Download arm gcc toolchain
#      run: |
#        sudo apt-get update
#        sudo apt-get install gcc-arm-none-eabi -y
    - name: Download python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: Download pros
      run: |
        pip install pros-cli
    - name: Build code
      run: |
        pros make

